var master=["APD",
"GOI",
"DNS",
"NPS",
"Sop",
"NSG",
"SQL",
"ECL",
"ETD",
"EVM",
"MCF",
"FTP",
"TCP",
"DDO",
"RBI",
"RAM",
"LWE",
"LPG",
"UAV",
"LED",
"UDP",
"CNP",
"PTZ",
"IOT",
"UNO",
"VIP",
"NISA",
"Riot",
"Fact",
"DFMD",
"Fire",
"Rape",
"Loan",
"Thug",
"Fuse",
"GAIL",
"Mint",
"Arms",
"RTGS",
"Lead",
"Hubs",
"Manu",
"CRPF",
"HHMD",
"LWEs",
"DRDO",
"Data",
"Mess",
"NEFT",
"Coin",
"ONGC",
"CISF",
"IEDS",
"PESC",
"PMIS",
"NHRC",
"BCAS",
"BCCL",
"IMAP",
"SDDL",
"IPv4",
"Coca",
"IPv6",
"VoIP",
"CCTV",
"CASO",
"Coal",
"VSSC",
"VTMS",
"Ping",
"Bond",
"Bomb",
"Laser",
"Opium",
"DASH7",
"Naxal",
"EDSAC",
"EDVAC",
"Audit",
"SOLAS",
"Fraud",
"Theft",
"OAuth",
"ENIAC",
"Funds",
"PFRDA",
"Crime",
"Range",
"Death",
"Zigbee",
"Siren",
"ONVIF",
"Ganja",
"WebID",
"Lease",
"Arson",
"Ulama",
"Radar",
"XACML",
"RSBAC",
"VISAS",
"Drugs",
"X-BIS",
"Mines",
"Pests",
"Chunk",
"Login",
"Affray",
"Apathy",
"Injury",
"Shovel",
"Bridge",
"Z-Wave",
"Budget",
"Murder",
"Sniper",
"Beacon",
"Server",
"Policy",
"Convoy",
"Sector",
"ISTRAC",
"STORES",
"SPMCIL",
"Dynamo",
"Modems",
"PERMIS",
"Agency",
"Strike",
"Macros",
"Keyway",
"Hammer",
"Ambush",
"Rubber",
"Escort",
"Troops",
"Cheque",
"Rocket",
"Gherao",
"Tappet",
"Torque",
"Reboot",
"OpenID",
"Viscera",
"Inquiry",
"Veranda",
"Custody",
"Mafia’s",
"Warrant",
"Economy",
"Hazards",
"Battery",
"Slander",
"LOGBOOK",
"Harbour",
"Typhoid",
"Dignity",
"Assault",
"Offence",
"Mileage",
"Spanner",
"Summons",
"Tsunami",
"Routers",
"Grinder",
"Illegal",
"Cyclone",
"Circuit",
"Grenade",
"MALARIA",
"Cholera",
"Salvage",
"Damodar",
"Barcode",
"Robbery",
"FIDO X2",
"Leakage",
"FIDO X3",
"Website",
"Retreat",
"Ledgers",
"Volcano",
"Tourism",
"Masonry",
"Foreign",
"Licence",
"Railway",
"Forgery",
"Bribery",
"Appeals",
"License",
"Malware",
"Computer",
"Linguist",
"Frigates",
"Friction",
"Topology",
"Armourer",
"Firearms",
"Gambling",
"Resource",
"Reveille",
"Lock-out",
"Switches",
"Cheating",
"Trespass",
"Evidence",
"Greasing",
"Euphoria",
"Grenades",
"Root kit",
"Epidemic",
"Opinions",
"Altitude",
"Humidity",
"Web page",
"Painting",
"Adultery",
"Bacteria",
"Bailable",
"Narcotic",
"Interpol",
"Scandisk",
"Steering",
"Prenatal",
"Security",
"Software",
"Diarrhea",
"Sedition",
"Policies",
"Internet",
"Deepface",
"Burglary",
"Database",
"MyriaNed",
"Industry",
"Mischief",
"Moisture",
"Turnstile",
"Integrity",
"Antivirus",
"Submarine",
"Gunpowder",
"Listening",
"Hepatitis",
"3D selfie",
"Telephone",
"Air India",
"Main Page",
"Ip reader",
"Complaint",
"Tornadoes",
"Radiation",
"Locksport",
"UNIVAC-1.",
"Cash Book",
"WebFinger",
"Bomb suit",
"Profiling",
"Generator",
"Sand bags",
"Artillery",
"Firewalls",
"Addiction",
"Explosive",
"Dog squad",
"Polygraph",
"Acts East",
"Technical",
"Pollution",
"Waveguide",
"Toll road",
"Incidents",
"Detonator",
"Corvettes",
"Cartridge",
"Circulars",
"Local law",
"Smuggling",
"Espionage",
"Terrorist",
"Terrorism",
"Water jet",
"Biometric",
"Equipment",
"Infection",
"Bit (key)",
"Vandalism",
"Cam shaft",
"Abduction",
"Gas stove",
"Pilferage",
"Insolvent",
"Intention",
"Haversack",
"Swing door",
"Lubricants",
"Minor Acts",
"Motivation",
"Gunn diode",
"Supervisor",
"Affidavits",
"Duty Posts",
"Topography",
"Capitalist",
"Web server",
"Token coin",
"Grsecurity",
"INT Manual",
"Conduction",
"Drip torch",
"Modulation",
"3D scanner",
"Section 10",
"Section 11",
"VISUALIZER",
"Hyperlinks",
"Mock Drill",
"Hurricanes",
"Convection",
"Minorities",
"RF Scanner",
"Government",
"Parliament",
"Detonation",
"Corruption",
"Magistrate",
"Appendices",
"Deputation",
"Flashpoint",
"Coal mafia",
"Defamation",
"Ammunition",
"Suggestion",
"Debit card",
"Accounting",
"Cognizable",
"Patrolling",
"Kidnapping",
"Dam bursts",
"Collective",
"Combustion",
"Commandant",
"Brasstacks",
"Earthquake",
"Arbitrator",
"Radicalism",
"Privileges",
"Toxicology",
"Battalions",
"Leadership",
"Cultivator",
"Web Browser",
"Crank shaft",
"Lubrication",
"Server room",
"Ip addresss",
"Pedestrians",
"Definitions",
"Counterfeit",
"Air Marshal",
"Phone calls",
"Photography",
"Sovereignty",
"Dishonestly",
"Ventilation",
"Special law",
"Institution",
"Speedometer",
"Information",
"Inflammable",
"SOFT SKILLS",
"Strong room",
"Arbitration",
"Lithography",
"Cloud Burst",
"Engineering",
"Environment",
"Indian Army",
"Warded lock",
"Cyber crime",
"LABOUR LAWS",
"Credit card",
"Pornography",
"Expiry date",
"Supervision",
"FABRICATION",
"Middle East",
"Armed Force",
"Resignation",
"Legal right",
"Leave Rules",
"Fitnano STS",
"Recycle Bin",
"Adolescence",
"Article 370",
"Full-duplex",
"Fund Manual",
"Timing gear",
"Procurement",
"Law & Order",
"Radiography",
"IT services",
"IEEE 802.15",
"Observation",
"McLeod Tool",
"Labour Laws",
"Action Plan",
"Card reader",
"CONTINGENCY",
"Addressable",
"High Courts",
"Visible zone",
"Stock holder",
"Condemnation",
"Riot pistols",
"Surface area",
"Safe custody",
"Armed forces",
"Insecticides",
"Multiplexers",
"Fingerprints",
"Boom barrier",
"Remuneration",
"Lock picking",
"Social media",
"Flag marches",
"Auction plan",
"Red Corridor",
"BOOM-BARRIER",
"Cooling suit",
"Fraudulently",
"Alarm device",
"Oil Industry",
"Convoy Drill",
"Police force",
"Unsound mind",
"Data masking",
"Data storage",
"Air Velocity",
"ALFA (XACML)",
"Assam Rifles",
"Provisioning",
"Adjudication",
"Shock, Burns",
"Access badge",
"Transparency",
"Civil courts",
"Photogravure",
"Space Sector",
"Case Studies",
"Dowry System",
"RANGE DUTIES",
"Labour Court",
"Criminal Law",
"CISF MANUALS",
"Pyrotechnics",
"Wireless USB",
"Skeleton key",
"Punched card",
"Public place",
"Human Rights",
"Non-bailable",
"ANT (network)",
"Email address",
"Access routes",
"Counterweight",
"Authorization",
"Fortification",
"Jurisdictions",
"Conduct Rules",
"Sati Practice",
"Investigation",
"Escape Routes",
"Weapon Sights",
"Logitech BRIO",
"Miscellaneous",
"Boolean Logic",
"Annual Budget",
"Duties of MTO",
"Cyberstalking",
"Bodily strain",
"Network Layer",
"Caution Money",
"Traffic signs",
"DRONE TRAPPER",
"General Diary",
"Wrongful loss",
"Wrongful gain",
"Tranquilizers",
"Supreme Court",
"Walkie Talkie",
"Pension Rules",
"Point of sale",
"Preservatives",
"TRAINING SUIT",
"RFID skimming",
"Gratification",
"Grave offence",
"Trojan horses",
"Service Books",
"Communication",
"Earnest money",
"IED AND SUITS",
"Capsi-Grenade",
"Fidelity bond",
"Search engine",
"Quarter Guard",
"HISTORY SHEET",
"Detection dog",
"Hand geometry",
"QUARTER GUARD",
"XBIS Machines",
"Door security",
"MT MANAGEMENT",
"Date of birth",
"Imaging radar",
"First aid kit",
"Navy Act,1957",
"Ionic Bonding",
"Civil Defence",
"Accountability",
"Police officer",
"Electric motor",
"Nervous system",
"Prime Minister",
"Facts in issue",
"Provident Fund",
"Revised Budget",
"False evidence",
"Smoke detector",
"Rubber Bullets",
"Proximity card",
"Deadly weapons",
"Single sign-on",
"Cyber Security",
"Public Account",
"Cyber security",
"Private sector",
"Magnetic field",
"Authentication",
"Logitech Group",
"MS POWER POINT",
"Non-cognizable",
"Army Act ,1950",
"Machine vision",
"Door breaching",
"Fire retardant",
"Routing tables",
"Metal detector",
"Relevant facts",
"Conveyor belt,",
"Arrest in CRPC",
"Civil aviation",
"Access control",
"Computer virus",
"Civil Disorder",
"Identity fraud",
"Dwelling house",
"Ultra-wideband",
"World Wide Web",
"ACCESS CONTROL",
"Barcode reader",
"Currency chest",
"QUARTER MASTER",
"Data structure",
"Reconnaissance",
"Nanotechnology",
"Scene of crime",
"Temporary file",
"Foreign policy",
"Digital device",
"Security alarm",
"Public servant",
"Modus operandi",
"Public Servant",
"Public auction",
"Cyberterrorism",
"Semaphore line",
"Hurricane lamp",
"Sanik Sammelan",
"English Channel",
"Election Duties",
"Lashkar-E-Toiba",
"Training Manual",
"Accounts Manual",
"Trade union act",
"Proved evidence",
"Radio frequency",
"IR Ray detector",
"Radio telephony",
"Torpedo service",
"Force personnel",
"Flatbed scanner",
"Union territory",
"First responder",
"Tear Gas Shells",
"Finger tracking",
"MOTOR TRANSPORT",
"Online bullying",
"Optical scanner",
"Surface tension",
"Ext4 filesystem",
"Area domination",
"Motor transport",
"Trusted systems",
"Electromagnetic",
"Electoral Right",
"Industrial Fire",
"Public nuisance",
"Police act,1861",
"Burden of proof",
"Budget Estimate",
"Stolen property",
"Border outposts",
"Aggrieved woman",
"Concertina wire",
"Moral turpitude",
"Scheduled tribe",
"Sovereign state",
"Abetting mutiny",
"Perimeter fence",
"Security threat",
"Defragmentation",
"Mistake of fact",
"Decision Making",
"Vote on account",
"Award of Medals",
"Shift in-charge",
"Smart card quiz",
"Radio broadcasts",
"Place of quizzes",
"Pin tumbler lock",
"Technical Manual",
"Natural disaster",
"Cisf act of 1983",
"3D body scanning",
"Movable Property",
"Drug trafficking",
"Driving Practice",
"UNIT- 5 SEAPORTS",
"Search operation",
"Physical Contact",
"Secret Enquiries",
"Polling stations",
"COBRA 3WAY SPRAY",
"Security gadgets",
"Security patches",
"Pers. management",
"Organic solvents",
"LOGITECH MEET-UP",
"Gazetted Officer",
"Social etiquette",
"Operating system",
"COBRA TERMINATOR",
"Iris recognition",
"Smoke inhalation",
"The Red Corridor",
"Court of Justice",
"Computer network",
"Money laundering",
"President’s Rule",
"COMPUTER SYSTEMS",
"Computer program",
"Machine learning",
"Official Gazette",
"Cyber defamation",
"Culpable homicide",
"CCS Conduct Rules",
"Technical Gadgets",
"Computer security",
"Siliguri Corridor",
"SiPass integrated",
"Computer hardware",
"Attempt to murder",
"Motor Vehicle Act",
"INDIAN PENAL CODE",
"Infirmity of mind",
"INFORMATION KIOSK",
"Electronic device",
"Ordinary passport",
"Flammable liquids",
"Nuclear disasters",
"Valuable security",
"Ethics and values",
"Stored value card",
"Physical security",
"UNLAWFUL ASSEMBLY",
"Electronic record",
"National Tribunal",
"Maintenance Of SR",
"Man made disaster",
"Fibers and fabric",
"USB plug-and-play",
"Technical gadgets",
"Duties of cashier",
"Telecommunication",
"Hands on computer",
"Stress management",
"Official passport",
"Purchase register",
"UNIT- 4 DAE & DoS",
"Training Material",
"Chemical reaction",
"Welded fire fence",
"Acts of vandalism",
"Communal Violence",
"Fire Extinguisher",
"Sec. 45 of Cr.P.C",
"Service etiquette",
"Pathological liar",
"Royal Indian Navy",
"Full body scanner",
"Rebellion of 1857",
"Search and locate",
"Unlawful assembly",
"Optical turnstile",
"Dying declaration",
"Aska Dragon Light",
"Threat perception",
"Microwave sensors",
"Thermal resistance",
"Aircraft hijacking",
"Wafer tumbler lock",
"White collar crime",
"Passive Resistance",
"Authorization hold",
"Pay and allowances",
"Perimeter security",
"Air Force Act,1950",
"Authorization OSID",
"Inspection of mess",
"Information hiding",
"Unnatural offences",
"Unit –I Operations",
"President of India",
"Immovable property",
"National Tribunals",
"Hypothetical story",
"LOGITECH PTZ PRO 2",
"Purchase committee",
"CPR with practical",
"Canteen Fund Rules",
"Government servant",
"Goods and Services",
"Transmitting power",
"Medals and ribbons",
"Chain-link fencing",
"Chain link fencing",
"Fundamental rights",
"PERIMETER SECURITY",
"The arms act, 1959",
"Operational Manual",
"Relevancy of facts",
"Fire alarm systems",
"Leave Rules Precie",
"Reporting of crime",
"Target acquisition",
"Reserve battalions",
"Armed insurrection",
"Federated identity",
"Tactical formation",
"Right to education",
"Factories act,1948",
"Exercise Shoorveer",
"Evidence of a fact",
"RubberBall Bullets",
"Electronic sensors",
"Antivirus software",
"Eddystone (Google)",
"East India Company",
"Duties of mess PMC",
"Duties of Gate I/C",
"Digital Signatures",
"Debris and trashes",
"Welfare Fund Rules",
"Dead Letter Office",
"Damage to property",
"DESIGN OF TRAINING",
"Gender Sensitivity",
"Contactless payment",
"SUPERVISION OF MESS",
"Cheating & mischief",
"Optical fiber cable",
"Night Vision device",
"Explosive detection",
"Water extinguishers",
"INDIAN EVIDENCE ACT",
"Contract of service",
"Diplomatic passport",
"Disaster Management",
"Labour intelligence",
"Indian Evidence Act",
"Provisioning Manual",
"District Magistrate",
"Theory of computers",
"Gesture recognition",
"Pedestrian crossing",
"Commercial Aviation",
"Harbouring deserter",
"Abetment of suicide",
"Disaster management",
"Functioning of mess",
"Dacoity with murder",
"Paramilitary Forces",
"Election Commission",
"Lethal/Deadly Force",
"Sashastra Seema Bal",
"Counterintelligence",
"Crime investigation",
"Criminal conspiracy",
"Case Studies of GBS",
"Identity management",
"Microsoft Word 2007",
"Access control list",
"Organization Manual",
"Detonation velocity",
"Duties of Shift I/C",
"Chief of Army Staff",
"XMIS Mail Scan 5030",
"Trusted third party",
"Anti- UAV Equipment",
"Competent authority",
"Morale of the Force",
"Financial statement",
"Logitech Smart-Dock",
"Quick Response Team",
"Insurgency in India",
"Causing miscarriage",
"Magnetic strip card",
"Intelligence Bureau",
"Quantum computation",
"Annexures/Appendices",
"Lightening conductor",
"Atomic Authorization",
"Customs of the Force",
"Cover, alibi & alias",
"Ip access controller",
"Counterfeiting notes",
"Automatic swing gate",
"Security engineering",
"Passive Night Google",
"Security Pass System",
"Bluetooth low energy",
"Solitary confinement",
"Computer application",
"Education Fund Rules",
"Rule of thumb method",
"Insensitive munition",
"Clothing & equipment",
"Information security",
"Indian coal industry",
"Civil administration",
"Night vision devices",
"Incident Action Plan",
"Establishment Manual",
"System administrator",
"TRAINING METHODOLOGY",
"Microsoft Excel 2007",
"Ignition temperature",
"Privilege escalation",
"Financial statements",
"Firewall (computing)",
"Passive Night Google",
"Travelling Allowance",
"UNIT 2 CISF ACT 1968",
"Anti-social elements",
"UNIT- 3 STEEL SECTOR",
"Manufacturing process",
"Public Address System",
"HOLDFAST COOLING SUIT",
"UNIT 3 CISF RULE 1968",
"Giving false evidence",
"Case Studies of metro",
"RUN-FLAT Tire Systems",
"Training Institutions",
"Tokyo Convention 1963",
"Regimental Fund Rules",
"Methods of extinction",
"Procedure for advance",
"Privilege (computing)",
"Adulteration of drugs",
"Important Definitions",
"Charge-coupled device",
"Preparation of budget",
"Punishment for murder",
"Incomplete combustion",
"Border Security Force",
"OFFICE ADMINISTRATION",
"Aids of interrogation",
"Intellectual property",
"SYSTEM OF PROCUREMENT",
"Sabotage & Subversion",
"Dowry Prohibition Act",
"Section-57 of Cr.P.C.",
"Intelligence agencies",
"Biographical research",
"PROTOCOL FOR TRAINEES",
"PAPER-VIII OPERATIONS",
"Data-centric security",
"Attribute (computing)",
"Signature recognition",
"Criminal intimidation",
"Atta kneading machine",
"Military intelligence",
"Lock (security device)",
"DUTIES OF KOTE OFFICER",
"Political intelligence",
"Corroborative evidence",
"Criminal Impersonation",
"XBIS Inner Vision 6040",
"Punishment for rioting",
"Automatic sliding gate",
"Types of transmissions",
"Types of extinguishers",
"GLOBUS INTERACTIVE PAD",
"Series 3 EOD/IEDD suit",
"Regulating Act of 1773",
"Electronic Stethoscope",
"Gross domestic product",
"Mess & table etiquette",
"Gross national product",
"Information Technology",
"Electronic Stethoscope",
"XBIS inner Vision 5030",
"Destructive Adsorption",
"Operational efficiency",
"Allowance and Benefits",
"Infrared safety sensor",
"UNIT- 8 PRIVATE SECTOR",
"Emergency Alert System",
"Welded wire mesh fence",
"Security token service",
"Fire Finder XLS System",
"EVALUATION OF TRAINING",
"Trafficking in persons",
"Maintenance of dossier",
"Possession of property",
"Inspection of vehicles",
"Classified information",
"Fire sprinkler systems",
"Agricultural operation",
"Network interface card",
"Montréal Protocol 1988",
"TRAINING NEED ANALYSIS",
"Functioning of Unit QG",
"Keeping lottery office",
"Income tax on salaries",
"Wireless Communication",
"Remote dispense system",
"Chief Justice of India",
"Fence detection systems",
"VULKAN DISRUPTER SYSTEM",
"Identity based security",
"Millimeter wave scanner",
"Mess audit & inspection",
"Environmental disasters",
"Mob dispersal equipment",
"Charitable institutions",
"Welfare schemes in CISF",
"Anti-hijacking Act 1982",
"TRAINING ADMINISTRATION",
"Artificial intelligence",
"National Security Guard",
"Do’s and Don’ts for SOs",
"Making a false document",
"Minimum force by police",
"Vehicle checking drills",
"File system permissions",
"Non-govt. organizations",
"Psychotropic substances",
"MOTOR VEHICLE ACT, 1988",
"Code of Civil Procedure",
"CENTRAL CONTROL CONSOLE",
"Theft,extortion,robbery",
"Thermal imaging systems",
"Indian Penal Code, 1860",
"Information sensitivity",
"General Police Training",
"Introduction to MS Word",
"DRIVING AND MAINTENANCE",
"Research & Analysis Wing",
"President Mess Committee",
"XBIS Inner Vision 100100",
"Electronic eavesdropping",
"The Passports Act (1967)",
"Near field communication",
"Mandatory access control",
"Ministry of Home Affairs",
"Leader of the opposition",
"Vigilance Set Up in CISF",
"Functional filing system",
"Railway Protection Force",
"Psychological Resistance",
"Organizational Behaviour",
"Special Protection Group",
"Mk2 TACTICAL SEARCH SUIT",
"Denial of service attack",
"Chicago Conventions 1944",
"Intention (criminal law)",
"Criminal breach of trust",
"Explosive Trace detector",
"Quizzes of SecurityPedia",
"Case Studies of Seaports",
"Introduction to MS Excel",
"RIGHT OF PRIVATE DEFENCE",
"Service Level Agreements",
"Internal Security duties",
"Montréal Convention 1971",
"Government E-market Place",
"Identity (social science)",
"Procuration of minor girl",
"Indoor positioning system",
"Role based access control",
"Aska Baselite LED 300/600",
"Different fund sunder NGF",
"Search of arrested person",
"Risk-based authentication",
"Detonation flame arrester",
"Facial recognition system",
"Report writing – DSR, SSR",
"UNIT- 9 CURRENCY AND MINT",
"Tokyo Convention Act 1975",
"Falsification of accounts",
"Backscatter (photography)",
"Introduction to Sea Ports",
"Petrol oil and lubricants",
"Contingency Fund of India",
"The Hague Convention 1970",
"Capability-based security",
"MANAGEMENT OF CISF STORES",
"Role-based access control",
"General exceptions in IPC",
"XBIS Inner Vision 6040 HE",
"INFORMATION SECURITY QUIZ",
"Good faith, 52A – Harbour",
"Multi-party authorization",
"License plate recognition",
"Emergency response system",
"Video conferencing system",
"Video Surveillance System",
"Public Sector Undertakings",
"Determination of Seniority",
"Database management system",
"Electronic Reverse Auction",
"Personation at an election",
"Airport Authority of India",
"Identity driven networking",
"Consolidated Fund of India",
"Introduction to explosives",
"Intrusion Detection System",
"Comparison with other CAPF",
"Identity management system",
"Indo-Tibetan Border Police",
"Code of Criminal Procedure",
"Discipline & Appeal Manual",
"Duties of Control Room I/C",
"Refusing to sign statement",
"Unlawful compulsory labour",
"Verbal & non-verbal skills",
"VIRTUAL CLASSROOM SOLUTION",
"User provisioning software",
"IC, engine and their Parts",
"Graph-based access control",
"Public Information Officer",
"Labour management relations",
"Discipline and Legal Manual",
"The Trade Disputes Act,1929",
"VIDEO CONFERENCING SOLUTION",
"Registration of new vehicle",
"Improvised explosive device",
"Incident management concept",
"Ballistic missile submarine",
"Distributed control systems",
"National Informatics Centre",
"Using a false property mark",
"INTERACTIVE BOARD ( IB 80C)",
"Importance of communication",
"Different level of security",
"UNIT- 1 COAL, MINES & POWER",
"PIS data, PRAN card in CISF",
"Surface Mine Detectors VMH3",
"Mine countermeasure vessels",
"System Spectrum Guard : CTL",
"Svp National Police Academy",
"Types of account maintained",
"HIGH POWER BLANK CARTRIDGES",
"Internal Complaint committee",
"Countering of suicide bomber",
"Context-based access control",
"Personating a public servant",
"UNIT- 2 OIL & PETROCHEMICALS",
"Personnel Information System",
"Central Reserve Police Force",
"Furnishing false information",
"MT accident Reporting System",
"Introduction to Steel Sector",
"Actions Against Probationers",
"Introduction to Intelligence",
"Titles & definitions of CRPC",
"Lattice-based access control",
"Discretionary access control",
"Principle of least privilege",
"Conduct for Mahila employees",
"Plantations Labour Act, 1951",
"Industrial disputes act 1947",
"Grave and sudden provocation",
"National Crime Record Bureau",
"Recovery of Professional Tax",
"HFS Series III Training Suit",
"Case Studies of steel sector",
"Dissemination of information",
"DAK MONITORING OFFICE DUTIES",
"Rules Regarding Gift & Dowry",
"RW & Credit note/Air Voucher",
"MAINTENANCE OF STORES RECORDS",
"PAPER- IV INTRODUCTION TO LAW",
"Privileges of public servants",
"EOD/IED DISPOSAL BOMB BLANKET",
"Cloak-and-dagger secret agent",
"Attribute based acces control",
"The official secret act, 1923",
"Management and its Principles",
"Time and Resources Management",
"Personal protective equipment",
"Snake Bite Cases & Prevention",
"Criminal Procedure Code, 1973",
"Disturbing religious assembly",
"Location-based authentication",
"Cross occupational competency",
"Handling of suspicious object",
"Unit –II Intelligence in CISF",
"Disastrous fire in HEC Ranchi",
"Disaster Management Act, 2005",
"Rules of Road regulation 1989",
"Right to information act-2005",
"Sale of noxious food or drink",
"General conditions of service",
"National Commission for women",
"Aska High Pressure Mist & CAFS",
"Buried cable detection systems",
"Dispersal of unlawful assembly",
"System of provisioning in CISF",
"Restriction Regarding Marriage",
"SECTION 7 (1) OF CISF ACT 1969",
"Things done in private defence",
"Communication technical manual",
"Industrial Security Management",
"Case Studies of private sector",
"Mini Blitz Electronic Exploder",
"Confidence building activities",
"Active Fire Protection Systems",
"Surface-to-air missile systems",
"Aviation Security: An overview",
"Passive Night Vision Binocular",
"Case Studies of airport sector",
"Introduction to MS Power Point",
"Central Information Commission",
"FIRE PROTECTION AND MANAGEMENT",
"Non-governmental organizations",
"Radio frequency identification",
"Food nutrition and Balance Diet",
"UNIT - 3 Information Technology",
"Analysis and evaluation of bids",
"Wireless - History, use & risks",
"Working with internet and email",
"Interpersonal skill development",
"LOGITECH CONFERENCE CAM CONNECT",
"Forgery for purpose of cheating",
"Training & institutions in CISF",
"Force, assault & criminal force",
"Central Bureau of Investigation",
"Paper – V OFFICE ADMINISTRATION",
"Healthy and sanitary conditions",
"Countering of vehicle borne IED",
"CARE AND PRESERVATION OF STORES",
"Fire Service Training Institute",
"Duties of Duty Officer, SO, NCO",
"Counterfeiting Government stamp",
"Space reconnaissance technology",
"Dynamics of industrial security",
"The Industrial Dispute Act,1947",
"Act of a person of unsound mind",
"INTRODUCTION TO TRAINING MANUAL",
"Sexual harassment at work place",
"Message writing and transmission",
"UNLAWFUL ASSEMBLY, RIOTS, AFFRAY",
"First recorded success in flying",
"Crowd psychology & crowd control",
"Fire alarm operation and control",
"Using evidence known to be false",
"Case Studies of DAE & DOs sector",
"National Disaster Response Force",
"Dragon Light and lighting towers",
"Knowing When to Use RBAC vs ABAC",
"Causes of fire growth and spread",
"Maintenance of registers at Gate",
"Dealing with client & management",
"LEADERSHIP AND MANAGEMENT SKILLS",
"Condemnation and disposal policy",
"Holdfast SERIES 3+ EOD/IEDD SUIT",
"Tools, equipment and accessories",
"Medical attendance rules and CGHS",
"Waging, or attempting to wage war",
"Fund Manual & maintenance of NGFs",
"Organisation-based access control",
"Organisation based access control",
"UNIT - 2 Proficiency in Computers",
"Types of VISA & types of Passport",
"Case Studies of coal mines sector",
"Introduction to DAE & DoS Sectors",
"Transmission (telecommunications)",
"Case Studies of currency and mint",
"Unit-III Wireless & Communication",
"Central Industrial Security Force",
"Planning of expenditure of budget",
"Improvised Explosive Device (IED)",
"Important definitions in IPC,1860",
"Prevention and detection of Crime",
"Principles and necessity of audit",
"XBIS Inner Vision 5030 (Portable)",
"TECHNICAL BRANCH TECHNICAL MANUAL",
"Self awareness & self enhancement",
"Security Assertion Markup Language",
"JAMMER INTEGRATED WITH PTZ CAMERA:",
"Indian Space Research Organization",
"First Indian Airline Tata Sons Ltd",
"Contingency Plans & mock exercises",
"Three dimensional face recognition",
"Risk Premia Cum Saving Fund Scheme",
"Multi- Purpose Reflex Weapon Sight",
"Threat perception , escorting cash",
"Paper – VI INTERNAL ADMINISTRATION",
"Sale, etc., or obscene books, etc.",
"Duties of check-drawing DDO & RPAO",
"Methods of intelligence collection",
"Equal right to all Women employees",
"Recording of Statement (Practical)",
"Criminal trespass & house breaking",
"Threat of injury to public servant",
"National Securities Depository Ltd",
"Chairman Chiefs of Staff Committee",
"Physical verification/confirmation",
"Prevention of Corruption Act, 1988",
"Prevention of corruption act, 1988",
"CONDEMNATION AND DISPOSAL OF STORES",
"Guarding and Escorting of Valuables",
"Introduction to industrial security",
"Passive Night Sight For Rifle Ak-47",
"Short title extent and commencement",
"Purchase Of Goods Without Quotation",
"Personal Alert Safety System device",
"Medium Range thermal Imaging Camera",
"Purchase Of Goods By Obtaining Bids",
"Soft skills ; profiling at Airports",
"Making atmosphere noxious to health",
"Explosive Vapor and Trace detectors",
"Threat perception : Fire, pilferage",
"Community Based Disaster Management",
"Industrial Security Management Quiz",
"Security of Documents & Information",
"INTRODUCTION TO PROVISIONING MANUAL",
"OFFICE DUTIES OFFICE ADMINISTRATION",
"Effective communication with Troops",
"ORIGIN – GENESIS AND GROWTH OF CISF",
"INSTITUTIONAL FRAME WORK OF TRAINING",
"Alarm monitoring and control systems",
"Probation on Appointment / Promotion",
"Briefing and debriefing of the Shift",
"India’s internal security challenges",
"GFR provisions regarding procurement",
"Sale of counterfeit Government stamp",
"Physical security information system",
"Duties of Kote Officer - practical’s",
"Encapsulation (computer programming)",
"Duties & Responsibilities of Sectors",
"Relational database management system"];

function hasWord(original,word)
{
    // original=original.toLowerCase();
    // word=word.toLowerCase();
    return(original.indexOf(word))
}

function searchWords()
{
    var original=document.getElementsByTagName('textarea')[0].value;
    var count=0;
    for (var i = 0; i < master.length; i++)
    {
        var index=hasWord(original,master[i]);
        if (index!=-1)
        {
        	count++;
            //add [[]]
            original=original.substr(0,index)+"[["+original.substr(index,master[i].length)+"]]"+original.substr(index+master[i].length);
        }
    }
    document.getElementsByTagName('textarea')[0].value=original;
    console.log(count+" links");
}
searchWords();
